-- ui_copy rows removed (offers marketplace) — CHANGE for #308
insert into ui_copy(key,value) values ('admin_offer_margin_label','"mediBO Margin %"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('admin_offer_remove_btn','"Remove"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('admin_offer_restore_btn','"Restore"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('admin_offers_title','"Offer Listings"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_add_btn','"Add to Cart"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_added_to_cart','"Added to cart"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_cancel_btn','"Cancel"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_cart_badge','"Offer"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_chip_label','"Scheme available"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_create_title','"New Listing"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_delist_btn','"Remove Listing"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_discount_label','"Discount %"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_edit_title','"Edit Listing"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_end_date_label','"Offer Ends On"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_expiry_date_label','"Batch Expiry Date"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_hold_msg','"Held for your cart for {mins} minutes"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_hold_note','"Units are held for your cart for a short while"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_list_btn','"List an Offer"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_load_more','"Load more"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_match_label','"You order this"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_match_title','"Matched buyers"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_min_qty_label','"Min. Order Qty"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_min_qty_msg','"Minimum order is {qty} units"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_nav_label','"Offers"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_near_expiry_accept','"Yes, I understand"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_near_expiry_disclosure','"This product is near its expiry date. By adding it to your order, you confirm you have reviewed the expiry date and accept the terms of sale for short-dated stock."'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_near_expiry_title','"Short-dated stock"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_only_left_msg','"Only {qty} units available"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_pause_btn','"Pause"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_ptr_label','"Your PTR (₹)"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_push_btn','"Push to matched buyers"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_push_result_msg','"Sent to {sent} buyers, {skipped} skipped"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_qty_label','"Available Qty"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_restore_btn','"Restore"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_retry','"Retry"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_save_btn','"Save Changes"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_scheme_buy_label','"Buy Qty (e.g. 5)"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_scheme_free_label','"Free Qty (e.g. 1)"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_seller_label','"Sold by mediBO"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_sold_out','"Sold out"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_submit_btn','"Publish Listing"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_type_discount','"Offer"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_type_near_expiry','"Near Expiry"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_type_scheme','"Scheme"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_type_select','"Offer Type"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_unavailable','"This offer is no longer available"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_waitlist_btn','"Notify me"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_waitlist_toast','"We will message you when this offer is back"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offer_waitlisted_btn','"On waitlist"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offers_feed_empty','"No offers right now — check back soon"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offers_feed_title','"Offers"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('offers_forbidden','"Offers are available to approved pharmacies."'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('supplier_offers_empty','"No listings yet"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('supplier_offers_title','"My Listings"'::jsonb) on conflict (key) do nothing;
insert into ui_copy(key,value) values ('supplier_shell.tab_offers','"Offers"'::jsonb) on conflict (key) do nothing;
-- storefront_home_section row removed
insert into storefront_home_section(id,kind,title,ord,active) values ('short_dated_deals','short_dated','Short-dated deals',5,false) on conflict do nothing;
-- cron_task rows removed
insert into cron_task(name,mode,base_interval_s,work_sql,note) values ('offer-reservation-sweep','poll',300,'SELECT public._offer_reservation_sweep()','Releases an expired offer hold. Gate is the update''s own WHERE.') on conflict do nothing;
insert into cron_task(name,mode,base_interval_s,work_sql,note) values ('offer-expiry-cron','poll',3600,'SELECT public._offer_expiry_cron()','Expires a listing. Also woken by cron_signal when a listing''s qty or dates change.') on conflict do nothing;
insert into cron_task(name,mode,base_interval_s,work_sql,note) values ('offer-waitlist-notify','poll',600,'SELECT public._offer_waitlist_notify_cron()','Tells a waitlisted buyer stock is back. An empty waitlist is the common case.') on conflict do nothing;
insert into storefront_ui_label(key,value) values ('admin_offer_margin_label','mediBO Margin %') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('admin_offer_remove_btn','Remove') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('admin_offer_restore_btn','Restore') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('admin_offers_title','Offer Listings') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_add_btn','Add to Cart') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_added_to_cart','Added to cart') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_cancel_btn','Cancel') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_cart_badge','Offer') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_create_title','New Listing') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_delist_btn','Remove Listing') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_discount_label','Discount %') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_edit_title','Edit Listing') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_end_date_label','Offer Ends On') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_expiry_date_label','Batch Expiry Date') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_hold_msg','Held for your cart for {mins} minutes') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_hold_note','Units are held for your cart for a short while') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_list_btn','List an Offer') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_load_more','Load more') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_match_label','You order this') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_match_title','Matched buyers') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_min_qty_label','Min. Order Qty') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_min_qty_msg','Minimum order is {qty} units') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_nav_label','Offers') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_near_expiry_accept','Yes, I understand') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_near_expiry_disclosure','This product is near its expiry date. By adding it to your order, you confirm you have reviewed the expiry date and accept the terms of sale for short-dated stock.') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_near_expiry_title','Short-dated stock') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_only_left_msg','Only {qty} units available') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_pause_btn','Pause') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_ptr_label','Your PTR (₹)') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_push_btn','Push to matched buyers') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_push_result_msg','Sent to {sent} buyers, {skipped} skipped') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_qty_label','Available Qty') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_restore_btn','Restore') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_retry','Retry') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_save_btn','Save Changes') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_scheme_buy_label','Buy Qty (e.g. 5)') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_scheme_free_label','Free Qty (e.g. 1)') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_seller_label','Sold by mediBO') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_sold_out','Sold out') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_submit_btn','Publish Listing') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_type_discount','Offer') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_type_near_expiry','Near Expiry') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_type_scheme','Scheme') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_type_select','Offer Type') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_unavailable','This offer is no longer available') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_waitlist_btn','Notify me') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_waitlist_toast','We will message you when this offer is back') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offer_waitlisted_btn','On waitlist') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offers_feed_empty','No offers right now — check back soon') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offers_feed_title','Offers') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('offers_forbidden','Offers are available to approved pharmacies.') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('supplier_offers_empty','No listings yet') on conflict (key) do nothing;
insert into storefront_ui_label(key,value) values ('supplier_offers_title','My Listings') on conflict (key) do nothing;
