#!/usr/bin/env bash
# CHANGE #1016 — render the staff IA mapping (old feature → new home) from the
# backend's own nav_parity_report(). The table in docs/STAFF_IA_MAP.md is
# generated, never hand-written: re-run this after any registry change.
#   bash scripts/c1016_ia_map.sh            # rewrite docs/STAFF_IA_MAP.md
set -euo pipefail
cd "$(dirname "$0")/.."
DB="$(cat "${MEDIBO_DBURL_FILE:-$HOME/.medibo/dburl}")"
OUT=docs/STAFF_IA_MAP.md
psql "$DB" -At -F'|' -c "
  select r->>'old_key', r->>'old_label', r->>'old_surface', r->>'old_group', r->>'old_route',
         r->>'new_home', r->>'new_section', r->>'new_label', r->>'new_key', r->>'new_route', r->>'kind'
    from jsonb_array_elements(public.nav_parity_report()->'rows') r
   order by case r->>'new_home' when 'dashboard' then 1 when 'customers' then 2 when 'suppliers' then 3
                                when 'fulfill' then 4 when 'money' then 5 when 'more' then 6 else 9 end,
            r->>'new_section', r->>'new_label', r->>'old_key'" > /tmp/c1016_map.txt
TOTAL=$(psql "$DB" -Atc "select public.nav_parity_report()->>'total'")
UNRES=$(psql "$DB" -Atc "select public.nav_parity_report()->>'unresolved'")
{
  echo "# Staff app information architecture — CHANGE #1016"
  echo
  echo "Generated by \`scripts/c1016_ia_map.sh\` from \`nav_parity_report()\` on $(date -u +%Y-%m-%dT%H:%MZ)."
  echo "Every feature the registry held before the change, and the one home it has now."
  echo
  echo "- Baseline features: **$TOTAL** · unresolved: **$UNRES** (the rg rule \`c1016_parity_gate\` is red above 0)"
  echo "- Homes: Dashboard (see) · Customers (manage) · Suppliers (manage) · Fulfill (do) · Money (settle) · More (grid)"
  echo "- \`kept\` = the same row, re-homed · \`merged\` = a duplicate folded into the tile named under *New feature*"
  echo
  echo "| Old feature | Old label | Old surface · group | Old route | New home | New section | New label | New feature | New route | Kind |"
  echo "|---|---|---|---|---|---|---|---|---|---|"
  awk -F'|' '{printf "| `%s` | %s | %s · %s | `%s` | **%s** | %s | %s | `%s` | `%s` | %s |\n", $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11}' /tmp/c1016_map.txt
  echo
  echo "## Redirects (old route → new route)"
  echo
  echo "| From | To | Only role | Only without a subject | Why |"
  echo "|---|---|---|---|---|"
  psql "$DB" -At -F'|' -c "select from_route, to_route, coalesce(only_role,'all'), when_no_seed, coalesce(note,'') from public.nav_redirect order by from_route" \
    | awk -F'|' '{printf "| `%s` | `%s` | %s | %s | %s |\n", $1,$2,$3,$4,$5}'
} > "$OUT"
echo "c1016_ia_map: wrote $OUT ($TOTAL rows, $UNRES unresolved)"
