#!/usr/bin/env bash
# CHANGE #227 — regenerate SCOPE_AUDIT.md from the LIVE database.
#
# The audit table is not a document someone maintains by hand; it is
# public.scope_contract checked against the live function source by
# scope_contract_status(). This script prints that check as markdown so the
# result is readable in git as well as in the app (admin → More → Scope audit).
set -euo pipefail
ENV_FILE="${DEVRUNNER_ENV:-$HOME/mediBO-runner/runner.env}"
# shellcheck disable=SC1090
source "$ENV_FILE"
OUT="${1:-$(dirname "$0")/../SCOPE_AUDIT.md}"

rows=$(curl -sS -X POST "$SUPABASE_URL/rest/v1/rpc/scope_contract_status" \
  -H "apikey: $SERVICE_ROLE_KEY" -H "Authorization: Bearer $SERVICE_ROLE_KEY" \
  -H "Content-Type: application/json" --data '{}')

{
  echo "# SCOPE_AUDIT — date + zone scope, order → delivered"
  echo
  echo "Generated by \`scripts/gen_scope_audit.sh\` from the LIVE database."
  echo "Source of truth: \`public.scope_contract\` checked against the live"
  echo "function source by \`public.scope_contract_status()\`. The same data is"
  echo "rendered in the app at **admin → More → Scope audit**."
  echo
  echo "**The rule.** Scope controls what is DISPLAYED. Coverage, allocation,"
  echo "billing, payment matching, disputes and delivery always see the whole"
  echo "order, on every date and in every zone — an order placed yesterday still"
  echo "completes today. Every row marked *Exempt* below is exempt for that"
  echo "reason, and the rg guard \`flow_scope_contract\` keeps it that way."
  echo
  echo "Doors: \`scope_date(p)\` = coalesce(p, admin_active_date()) ·"
  echo "\`scope_zone(p)\` = coalesce(p, admin_active_zone()), where NULL means"
  echo "ALL zones · \`scope_zone_ok(row_zone, scope)\` — a row with an unknown"
  echo "zone is always visible."
  echo
  echo '| # | Stage | RPC | Surface | Date scope | Zone scope | Before | After | Note |'
  echo '|---|---|---|---|---|---|---|---|---|'
  jq -r 'sort_by(.stage_no, .rpc_name)[] |
    "| \(.stage_no) | \(.stage) | `\(.rpc_name)` | \(.surface) | " +
    (if .needs_date|not then "n/a"
     elif .date_mode=="asof" then "as-of active day"
     elif .date_mode=="label" then "labels only"
     else "active day" end) +
    (if (.needs_date and .has_date) then " ✅" elif .needs_date then " ❌" else "" end) +
    " | " + (if .needs_zone|not then "n/a" else "active zone" end) +
    (if (.needs_zone and .has_zone) then " ✅" elif .needs_zone then " ❌" else "" end) +
    " | \(.before_status) | \(.after_status) | \(.note) |"' <<<"$rows"
  echo
  printf '%s RPCs audited · %s scoped or exempt · %s broken.\n' \
    "$(jq 'length' <<<"$rows")" \
    "$(jq '[.[]|select(.ok)]|length' <<<"$rows")" \
    "$(jq '[.[]|select(.ok|not)]|length' <<<"$rows")"
} > "$OUT"
echo "wrote $OUT"
