#!/usr/bin/env bash
# CHANGE #821 — regenerate test/protected/registered_routes.dart from the DB.
#
# WHY THIS EXISTS. feature_registry and surface_route are the nav truth and
# they live in Postgres. The protected suite runs on the Dart VM with no
# network, so its copy of "which routes the shell must be able to open" is a
# checked-in file — and a checked-in mirror of a live table drifts. By #821 it
# was 31 routes behind, which is why the gate that exists to catch a tile with
# no door stayed green through the Feedback desk shipping without one.
#
# Keeping it in step is one command now instead of a memory:
#
#   bash scripts/gen_registered_routes.sh        # rewrite the file
#   bash scripts/gen_registered_routes.sh --check  # exit 1 if it is stale
#
# The other half of the loop is the rg payload target `c821_shell_doors`: any
# change to the door set moves that hash and turns rg_check RED, so the next
# runner is told to run this before rebaselining rather than discovering the
# drift a month later in a bug report.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT=test/protected/registered_routes.dart
DBURL_FILE="${MEDIBO_DBURL_FILE:-$HOME/.medibo/dburl}"
[ -f "$DBURL_FILE" ] || { echo "gen_registered_routes: no db url at $DBURL_FILE" >&2; exit 3; }
DB="$(cat "$DBURL_FILE")"

# The doors the Flutter shell itself is responsible for opening. handled_by is
# surface_route's own column, so a screen that moves to another handler leaves
# this list by itself.
SHELL_ROUTES=$(psql "$DB" -At -c "
  select string_agg(quote_literal(r.route_key), ', ' order by r.route_key)
    from (select distinct route_key from public.surface_route
           where is_active and handled_by = 'home_shell') r;")

# ...and the routes whose door is not a line of Dart at all: the shell hands
# them to AdminFulfillmentScreen on the stage the BACKEND pairs them with
# (access_boot().routes[].stage — an active surface='fulfill_tab' feature
# sharing the route's canonical key). Derived the same way access_boot derives
# it, so the two cannot disagree.
FULFILL_ROUTES=$(psql "$DB" -At -c "
  select string_agg(quote_literal(q.route_key), ', ' order by q.route_key) from (
    select distinct f.route_key
      from public.feature_registry f
     where f.is_active and coalesce(f.route_key,'') <> ''
       and exists (select 1 from public.feature_registry f2
                    where f2.is_active and f2.surface = 'fulfill_tab'
                      and coalesce(f2.canonical_key, f2.feature_key)
                          = coalesce(f.canonical_key, f.feature_key))) q;")

wrap() { printf '%s' "$1" | fold -s -w 74 | sed 's/^/  /; s/[[:space:]]*$//'; }

TMP="$(mktemp)"
cat > "$TMP" <<DART
// GENERATED by scripts/gen_registered_routes.sh — do not hand-edit.
//
// CHANGE #325 — the offline half of the feature registry.
// CHANGE #821 — generated from surface_route instead of remembered.
//
// \`feature_registry\` is the single source of nav truth, and it lives in
// Postgres. The protected suite runs on the Dart VM with no network, so it
// cannot read that table — this file is the frozen mirror it checks against.
//
// It used to be hand-maintained, and by #821 it had drifted 31 routes behind
// the registry: the Feedback desk (#697) shipped a tile, a screen and an RPC
// with no route in this list, so the gate that exists to catch exactly that
// stayed green. It is generated now, and \`c821_shell_doors\` (an rg payload
// target) turns any drift into a red rg_check for the next runner.
library;

/// Every \`route_key\` the SHELL is responsible for opening — surface_route
/// rows with handled_by = 'home_shell'. A route here must have a door in
/// \`home_shell.dart\`'s switch, an arm in \`shell/shell_extra_routes.dart\`, or
/// a fulfill pairing below; \`admin_nav_reachability_test.dart\` proves it.
const kRegisteredAdminRoutes = <String>[
$(wrap "$SHELL_ROUTES,")
];

/// CHANGE #754 / #821 — the routes whose door is the BACKEND's, not Dart's.
///
/// \`shellOpenFulfillStage\` sends these to AdminFulfillmentScreen on the stage
/// \`access_boot().routes[].stage\` pairs them with, so there is deliberately no
/// \`case\` and no shard arm for them to match. Listing them here is what lets
/// the reachability gate tell "routed by data" apart from "dead tap" — the
/// distinction it could not make before #821.
const kFulfillRedirectedRoutes = <String>[
$(wrap "$FULFILL_ROUTES,")
];
DART

if [ "${1:-}" = "--check" ]; then
  if diff -q "$OUT" "$TMP" >/dev/null 2>&1; then
    echo "gen_registered_routes: $OUT is in step with the registry"; rm -f "$TMP"; exit 0
  fi
  echo "gen_registered_routes: $OUT is STALE — run 'bash scripts/gen_registered_routes.sh' and commit it" >&2
  diff -u "$OUT" "$TMP" >&2 || true
  rm -f "$TMP"; exit 1
fi

mv "$TMP" "$OUT"
echo "gen_registered_routes: wrote $OUT"
