#!/usr/bin/env bash
# gen_repo_map.sh — CHANGE #198, LEVER 4 (context diet)
#
# Writes REPO_MAP.md: ONE line per source file — path → what it does → the RPCs
# it calls. A worker reads this map first and then opens only the handful of
# files its task actually touches, instead of grep -r'ing all of lib/ (which was
# costing ~200-400k input tokens on jobs that changed one widget).
#
# Deterministic, no network, ~1s. Run by deploy.sh on every deploy so the map
# can never drift from the tree it describes.
#
#   bash scripts/gen_repo_map.sh [outfile]      # default: REPO_MAP.md
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/REPO_MAP.md}"
cd "$ROOT"

# Per-section caps keep the map a map. They are applied PER SECTION (not to the
# whole file) so a long screens list can never decapitate the SQL or scripts
# sections below it — the failure mode of the first cut of this script.
MAX_LINES="${REPO_MAP_MAX_LINES:-400}"

# One-line purpose for a file: the first real doc comment, else the first
# class/function name, else the filename humanised. Never guesses.
purpose() { # <file>
  local f="$1" p=""
  case "$f" in
    *.dart)
      # leading /// doc comment on the file or its first declaration
      p="$(grep -m1 -E '^\s*///\s*\S' "$f" 2>/dev/null | sed -E 's@^\s*///\s?@@' || true)"
      [ -z "$p" ] && p="$(grep -m1 -E '^\s*//\s*\S' "$f" 2>/dev/null | sed -E 's@^\s*//\s?@@' || true)"
      [ -z "$p" ] && p="$(grep -m1 -oE '^(class|mixin|enum|extension) [A-Za-z0-9_]+' "$f" 2>/dev/null || true)"
      ;;
    *.sql)
      p="$(grep -m1 -E '^\s*--\s*\S' "$f" 2>/dev/null | sed -E 's@^\s*--\s?@@' || true)"
      ;;
    *.sh)
      p="$(sed -n '2,6p' "$f" 2>/dev/null | grep -m1 -E '^#\s*\S' | sed -E 's@^#\s?@@' || true)"
      ;;
    *.ts|*.js)
      p="$(grep -m1 -E '^\s*//\s*\S' "$f" 2>/dev/null | sed -E 's@^\s*//\s?@@' || true)"
      ;;
  esac
  [ -z "$p" ] && p="$(basename "$f" | sed -E 's/\.[a-z]+$//; s/_/ /g')"
  # collapse whitespace, trim to one readable clause.
  #
  # `cut -c` counts BYTES despite the flag name, so a cut landing inside a
  # multibyte character left a half em-dash in the map — one invalid byte makes
  # `grep` treat the WHOLE file as binary and print nothing, so every worker's
  # map lookup silently returned zero hits and they fell back to grepping the
  # repo. That is precisely the cost CHANGE #198 removed, reintroduced by a
  # comment full of box-drawing characters (#224). `iconv -c` drops any partial
  # sequence the cut created, so the map is always valid UTF-8 and greppable.
  printf '%s' "$p" | tr '\n' ' ' | sed -E 's/\s+/ /g; s/^ //; s/ $//' \
    | cut -c1-110 | iconv -f UTF-8 -t UTF-8 -c
}

# Distinct Supabase RPC names a file calls, comma separated (max 6).
rpcs() { # <file>
  grep -ohE "rpc\(\s*'[a-z0-9_]+'|\.rpc\(\"[a-z0-9_]+\"" "$1" 2>/dev/null \
    | sed -E "s@.*['\"]([a-z0-9_]+)['\"].*@\1@" \
    | sort -u | head -6 | paste -sd, - || true
}

# Exported top-level symbols, comma separated (max 5).
exports() { # <file>
  case "$1" in
    *.dart) grep -ohE '^(class|mixin|enum|extension) [A-Za-z0-9_]+' "$1" 2>/dev/null \
              | awk '{print $2}' | sort -u | head -5 | paste -sd, - || true ;;
    *.sql)  grep -ohE 'CREATE (OR REPLACE )?(FUNCTION|TABLE|VIEW) [a-zA-Z0-9_.]+' "$1" 2>/dev/null \
              | awk '{print $NF}' | sed 's/(.*//; s/^public\.//' | sort -u | head -5 | paste -sd, - || true ;;
    *)      printf '' ;;
  esac
}

section() { # <title> <cap> <find-args...>
  local title="$1" cap="$2"; shift 2
  local files n; files="$(eval "$@" | sort)"
  n="$(printf '%s\n' "$files" | grep -c '' || true)"
  [ -z "$files" ] && return 0
  printf '\n## %s\n\n' "$title" >>"$OUT"
  local f why call exp line
  while IFS= read -r f; do
    [ -z "$f" ] && continue
    why="$(purpose "$f")"
    call="$(rpcs "$f")"
    exp="$(exports "$f")"
    line="- \`${f#./}\` — ${why}"
    [ -n "$exp" ]  && line="$line · exports: ${exp}"
    [ -n "$call" ] && line="$line · rpc: ${call}"
    printf '%s\n' "$line" >>"$OUT"
  done <<<"$(printf '%s\n' "$files" | head -n "$cap")"
  if [ "$n" -gt "$cap" ]; then
    printf '_… %s more files in this tree — list them with `find` when the map is not enough._\n' \
      "$(( n - cap ))" >>"$OUT"
  fi
}

COMMIT="$(git rev-parse --short HEAD 2>/dev/null || echo unknown)"

cat >"$OUT" <<HEADER
# REPO_MAP — mediBO source index (generated)

Generated by \`scripts/gen_repo_map.sh\` on every deploy. Commit \`$COMMIT\`.

**Workers: read this file FIRST.** Find the handful of files your task touches,
then open ONLY those. Do not \`grep -r\` across all of \`lib/\` — that scan alone
costs more input tokens than most commands are worth. Fall back to a search only
when a map lookup genuinely fails, and say so in your build log.

Format: \`path\` — what it does · exports: top-level symbols · rpc: Supabase
functions it calls.
HEADER

section "Flutter — screens (\`lib/screens\`)" 120 \
  "find lib/screens -name '*.dart' -not -path '*/.*'"
section "Flutter — widgets, services, models (\`lib\`)" 180 \
  "find lib -maxdepth 2 -name '*.dart' -not -path 'lib/screens/*'"
section "Supabase — migrations (\`supabase/migrations\`)" 20 \
  "find supabase/migrations -name '*.sql'"
section "Supabase — edge functions (\`supabase/functions\`)" 15 \
  "find supabase/functions -name 'index.ts'"
section "Scripts (\`scripts\`, \`tool\`)" 25 \
  "find scripts tool -name '*.sh' -o -path 'tool/*' -name '*.dart'"
section "Protected tests (\`test/protected\`)" 40 \
  "find test/protected -name '*.dart'"

# Guard rail only — per-section caps above do the real work. If the tree grows
# past MAX_LINES the map still prints in full but says so, because a SILENTLY
# truncated map sends a worker grepping the repo, which is the cost we removed.
total="$(grep -c '' "$OUT")"
if [ "$total" -gt "$MAX_LINES" ]; then
  printf '\n_Map is %s lines (soft limit %s) — tighten the per-section caps in scripts/gen_repo_map.sh._\n' \
    "$total" "$MAX_LINES" >>"$OUT"
fi

echo "REPO_MAP: $(grep -c '' "$OUT") lines → $OUT"
