// GENERATED by scripts/gen_registered_routes.sh — do not hand-edit.
//
// SIX HAND-ADDED ENTRIES: CHANGE #639 'triage', CMD #1910
// 'admin_conditions' (Admin -> Uses & conditions), CMD #1929
// 'payment_alerts', CMD #1932 'advance_slabs' (the advance ladder), CMD
// #1935 'customer_doc_types' (Admin -> Customer documents) and CMD #1936
// 'onboarding_notices' (Admin -> Onboarding notices) — all six for the same
// reason and by the same rule. The surface_route INSERTs are in
// supabase/migrations/20260906060000_c639_triage_loop.sql,
// supabase/migrations/20260912204000_c1910_conditions_nav.sql,
// supabase/migrations/20260912120000_cmd1929_payment_alerts.sql,
// supabase/migrations/20260913093000_c1932_advance_ladder.sql,
// supabase/migrations/20260913120000_c1935_customer_docs.sql and
// supabase/migrations/20260914090000_c1936_onboarding_wa_triggers.sql; the
// next regeneration after deploy produces this same file.
//
// The #639 note, verbatim, because it is the rule: The generator reads
// surface_route from ~/.medibo/dburl, and a build runs against a BUILD BRANCH
// whose surface_route is empty — regenerating there would have replaced ~200
// routes with the one row this change inserts. Production could not be read
// either: a build must not touch it, and it does not carry the row until this
// migration replays. The next regeneration after deploy produces this same
// file; the surface_route INSERT is in
// supabase/migrations/20260906060000_c639_triage_loop.sql.
//
// CHANGE #325 — the offline half of the feature registry.
// CHANGE #821 — generated from surface_route instead of remembered.
//
// `feature_registry` is the single source of nav truth, and it lives in
// Postgres. The protected suite runs on the Dart VM with no network, so it
// cannot read that table — this file is the frozen mirror it checks against.
//
// It used to be hand-maintained, and by #821 it had drifted 31 routes behind
// the registry: the Feedback desk (#697) shipped a tile, a screen and an RPC
// with no route in this list, so the gate that exists to catch exactly that
// stayed green. It is generated now, and `c821_shell_doors` (an rg payload
// target) turns any drift into a red rg_check for the next runner.
library;

/// Every `route_key` the SHELL is responsible for opening — surface_route
/// rows with handled_by = 'home_shell'. A route here must have a door in
/// `home_shell.dart`'s switch, an arm in `shell/shell_extra_routes.dart`, or
/// a fulfill pairing below; `admin_nav_reachability_test.dart` proves it.
const kRegisteredAdminRoutes = <String>[
  'add_customer', 'add_medicine', 'add_supplier', 'admin_conditions',
  'admin_push', 'advance_slabs',
  'admin_roles', 'audit_log', 'bags', 'bill_pipeline', 'bulk_actions',
  'catalogue_health', 'companies', 'cron_health', 'cust_help_requests',
  'cust_reorder_due', 'cust_saved_lists', 'customers', 'damage_report',
  'dashboard', 'deletion_requests', 'delivery_extras', 'delivery_ops',
  'delivery_partners', 'delivery_waves', 'demand_engine', 'dev_queue',
  'discount_slabs', 'exceptions', 'exports', 'feature_gaps', 'feedback',
  'fulfil_tasks', 'fulfillment', 'gst', 'home', 'kyc_review', 'logout',
  'loyalty', 'manage_admins', 'money', 'money_home', 'more', 'mr',
  'my_shop', 'my_tasks', 'notify_center', 'notify_cost', 'ops_board',
  'ops_queues', 'order_alerts', 'order_closure', 'order_cutoff',
  'order_threads',
  'order_timeline', 'paper_sale', 'partner_documents', 'partner_expenses',
  'partner_issues', 'partner_scorecard', 'partner_scorecards',
  'partner_settlement', 'partner_staff', 'partner_workers',
  'partner_zone_pnl', 'payment_upi', 'pharmacy_audit', 'pharmacy_gst',
  'pharmacy_owner', 'pharmacy_radar', 'pharmacy_reorder', 'pharmacy_stock',
  'payment_alerts',
  'customer_doc_types',
  'onboarding_notices',
  'pharmacy_vault', 'pnl', 'pos', 'pos_upi', 'price_check', 'pricing',
  'pricing_backfill', 'profile', 'purchases', 'recon', 'reorder',
  'returns_refunds', 'reviews', 'scope_audit', 'search', 'search_synonyms',
  'settlement', 'settlement_invoices', 'supplier_accounts',
  'supplier_payment', 'supplier_returns', 'suppliers', 'surface_map',
  'test_mode', 'triage', 'unmapped_companies', 'users_access',
  'wa_assistant',
  'wa_campaigns', 'wa_diagnosis', 'wa_drips', 'wa_ops', 'wa_segments',
  'wa_templates', 'whatsapp', 'zone_pnl',
];

/// CHANGE #754 / #821 — the routes whose door is the BACKEND's, not Dart's.
///
/// `shellOpenFulfillStage` sends these to AdminFulfillmentScreen on the stage
/// `access_boot().routes[].stage` pairs them with, so there is deliberately no
/// `case` and no shard arm for them to match. Listing them here is what lets
/// the reachability gate tell "routed by data" apart from "dead tap" — the
/// distinction it could not make before #821.
const kFulfillRedirectedRoutes = <String>[
  'assign_delivery', 'bag', 'bag_mapping', 'collect', 'count',
  'customer_order', 'customer_orders', 'delivery', 'dispute', 'disputes',
  'exceptions', 'inquiry', 'ops_board', 'pack', 'supplier_inquiry',
  'supplier_order', 'supplier_orders', 'supplier_shop', 'warehouse',
];
