// GENERATED by scripts/gen_registered_routes.sh — do not hand-edit.
//
// CHANGE #325 — the offline half of the feature registry.
// CHANGE #821 — generated from surface_route instead of remembered.
//
// `feature_registry` is the single source of nav truth, and it lives in
// Postgres. The protected suite runs on the Dart VM with no network, so it
// cannot read that table — this file is the frozen mirror it checks against.
//
// It used to be hand-maintained, and by #821 it had drifted 31 routes behind
// the registry: the Feedback desk (#697) shipped a tile, a screen and an RPC
// with no route in this list, so the gate that exists to catch exactly that
// stayed green. It is generated now, and `c821_shell_doors` (an rg payload
// target) turns any drift into a red rg_check for the next runner.
library;

/// Every `route_key` the SHELL is responsible for opening — surface_route
/// rows with handled_by = 'home_shell'. A route here must have a door in
/// `home_shell.dart`'s switch, an arm in `shell/shell_extra_routes.dart`, or
/// a fulfill pairing below; `admin_nav_reachability_test.dart` proves it.
const kRegisteredAdminRoutes = <String>[
  'add_customer', 'add_medicine', 'add_supplier', 'admin_push',
  'admin_roles', 'audit_log', 'bags', 'bill_pipeline', 'bulk_actions',
  'catalogue_health', 'companies', 'cron_health', 'cust_help_requests',
  'cust_reorder_due', 'cust_saved_lists', 'customers', 'dashboard',
  'deletion_requests', 'delivery_extras', 'delivery_ops',
  'delivery_partners', 'delivery_waves', 'demand_engine', 'dev_queue',
  'discount_slabs', 'exceptions', 'exports', 'feature_gaps', 'feedback',
  'fulfil_tasks', 'fulfillment', 'gst', 'home', 'logout',
  'loyalty', 'manage_admins', 'money', 'mr', 'my_shop', 'my_tasks',
  'notify_center', 'notify_cost', 'ops_board', 'ops_queues',
  'order_alerts', 'order_closure', 'order_timeline', 'paper_sale',
  'payment_upi', 'pharmacy_audit', 'pharmacy_gst', 'pharmacy_owner',
  'pharmacy_radar', 'pharmacy_reorder', 'pharmacy_stock', 'pharmacy_vault',
  'pnl', 'pos', 'pos_upi', 'price_check', 'pricing', 'pricing_backfill',
  'profile', 'purchases', 'reorder', 'returns_refunds', 'reviews',
  'scope_audit', 'search', 'settlement', 'supplier_accounts', 'suppliers',
  'surface_map', 'test_mode', 'unmapped_companies', 'users_access',
  'wa_campaigns', 'wa_diagnosis', 'wa_drips', 'wa_ops', 'wa_segments',
  'wa_templates', 'whatsapp',
];

// CHANGE #707: 'kyc_review' is DELIBERATELY absent. surface_route declared it
// at 13:16 IST today for #705, whose Dart arm is still on that command's
// branch — so the generator emits it while `main` has no door for it, and the
// gate below correctly calls it an orphan. #705 regenerates this file when it
// lands its arm; a command that ships its own two doors does not get to fail
// the build on somebody else's half-landed one, and it does not get to switch
// their declaration off either. Re-run scripts/gen_registered_routes.sh after
// #705 merges and this line goes away by itself.

/// CHANGE #754 / #821 — the routes whose door is the BACKEND's, not Dart's.
///
/// `shellOpenFulfillStage` sends these to AdminFulfillmentScreen on the stage
/// `access_boot().routes[].stage` pairs them with, so there is deliberately no
/// `case` and no shard arm for them to match. Listing them here is what lets
/// the reachability gate tell "routed by data" apart from "dead tap" — the
/// distinction it could not make before #821.
const kFulfillRedirectedRoutes = <String>[
  'assign_delivery', 'bag', 'bag_mapping', 'collect', 'count',
  'customer_order', 'customer_orders', 'delivery', 'dispute', 'disputes',
  'exceptions', 'inquiry', 'ops_board', 'pack', 'supplier_inquiry',
  'supplier_order', 'supplier_orders', 'supplier_shop', 'warehouse',
];
