insert into public.ui_copy(key, value) values
 ('notify.heading','"Notification Centre"'::jsonb),
 ('notify.subheading','"Every message mediBO sends goes out through one dispatcher. WhatsApp is the only channel today."'::jsonb),
 ('notify.range_label','"Last {a} hours"'::jsonb),
 ('notify.summary_label','"{a} sent · {b} failed · {c} waiting"'::jsonb),
 ('notify.pending_label','"{a} waiting to be retried"'::jsonb),
 ('notify.dead_label','"{a} gave up after every retry"'::jsonb),
 ('notify.threshold_label','"An alert is raised when more than {a}% of an event fails within an hour"'::jsonb),
 ('notify.alerts_heading','"Needs attention"'::jsonb),
 ('notify.alerts_empty','"No event is failing right now."'::jsonb),
 ('notify.alert_body','"{a}% not delivered — {b} of {c} in the last hour"'::jsonb),
 ('notify.events_heading','"Events"'::jsonb),
 ('notify.events_empty','"No notification routes are configured yet."'::jsonb),
 ('notify.count_label','"{a} sent · {b} not delivered"'::jsonb),
 ('notify.state_off','"Off"'::jsonb),
 ('notify.state_no_template','"On — no template"'::jsonb),
 ('notify.state_live','"Live"'::jsonb),
 ('notify.no_template','"No template linked yet"'::jsonb),
 ('notify.channel_whatsapp','"WhatsApp"'::jsonb),
 ('notify.preview_action','"Preview"'::jsonb),
 ('notify.test_action','"Send me a test"'::jsonb),
 ('notify.retry_now','"Retry waiting messages"'::jsonb),
 ('notify.retry_done','"Tried {a} · sent {b}"'::jsonb),
 ('notify.preview_heading','"Preview"'::jsonb),
 ('notify.preview_empty','"Nothing to preview until a template is linked."'::jsonb),
 ('notify.no_body','"This route has no template body yet."'::jsonb),
 ('notify.tpl_approved','"Approved by Meta"'::jsonb),
 ('notify.tpl_pending','"Template is {a} — not sendable yet"'::jsonb),
 ('notify.tpl_none','"No template linked yet"'::jsonb),
 ('notify.unknown_event','"There is no route called {a}."'::jsonb),
 ('notify.not_authorized','"Only an admin can open the Notification Centre."'::jsonb),
 ('notify.no_test_number','"Add a WhatsApp number to your admin profile (or set admin_wa_phone) to test-send."'::jsonb),
 ('notify.test_supplier_blocked','"That number belongs to a supplier. Test messages are never sent to suppliers."'::jsonb),
 ('notify.test_sent_to','"Test sent to {a}"'::jsonb),
 ('notify.test_ok','"Sent — check your WhatsApp in a moment."'::jsonb),
 ('notify.test_failed','"Could not send: {a}"'::jsonb),
 ('notify.window_no_phone','"No WhatsApp number on file"'::jsonb),
 ('notify.window_never','"Never written to us — approved template only"'::jsonb),
 ('notify.window_open_for','"Free-form allowed for another {a}"'::jsonb),
 ('notify.window_closed','"Window closed — approved template only"'::jsonb),
 ('admin_nav.overflow_notify_center','"Notification Centre"'::jsonb)
on conflict (key) do update set value = excluded.value, updated_at = now();
