-- ============================================================================
-- CHANGE #306 — every word the alert says. Editing a label here changes the
-- popup, the lock-screen notification, the sticky tray line, the WhatsApp
-- escalation and the block messages with no deploy and no rebuild.
-- ============================================================================
update public.order_alert_config
   set labels = coalesce(labels,'{}'::jsonb) || $lbl${
  "push_title": "New order · {{customer}}",
  "push_body": "{{order_code}} · {{amount}} · UNPAID — accept to start the inquiry",
  "push_title_critical": "STILL WAITING · {{customer}}",
  "push_body_critical": "{{order_code}} · {{amount}} · unactioned for {{age}}",
  "accept_label": "Accept",
  "reject_label": "Reject",
  "dismiss_label": "Later",
  "view_label": "Open order",
  "ongoing_title": "{{count}} orders awaiting action",
  "ongoing_title_one": "1 order awaiting action",
  "ongoing_body": "Tap to review. They keep ringing until actioned.",
  "channel_name": "New order alerts",
  "channel_description": "Rings over the lock screen when an unpaid order needs a decision.",
  "banner_unpaid": "UNPAID ORDER — needs your decision",
  "banner_unpaid_queued": "UNPAID ORDER — {{count}} waiting",
  "banner_prepaid": "Paid order — accepted automatically",
  "banner_critical": "CRITICAL — unactioned for {{age}}",
  "accept_note": "Accepting starts the supplier inquiry only. It does not authorise buying the stock.",
  "accept_note_blocked": "Accepting is blocked while this customer is over their limit.",
  "reject_note": "Rejects the order and releases anything reserved for it.",
  "credit_prepaid_only": "New customer — prepaid only. {{customer}} owes {{outstanding}}.",
  "credit_over_limit": "{{customer}} owes {{outstanding}} against a limit of {{limit}}.",
  "credit_ok": "Within credit limit.",
  "toast_accepted": "Order accepted — inquiry started.",
  "toast_rejected": "Order rejected.",
  "toast_blocked": "Blocked: {{reason}}",
  "toast_already": "Already actioned.",
  "badge_label": "{{count}}",
  "badge_tooltip": "{{count}} orders awaiting action",
  "empty_title": "Nothing waiting",
  "empty_body": "New unpaid orders appear here the moment they land.",
  "state_ringing": "Awaiting action",
  "state_accepted": "Accepted",
  "state_rejected": "Rejected",
  "state_expired": "Expired",
  "state_auto_cancelled": "Auto-cancelled",
  "stage_new": "New",
  "stage_rering": "Re-ringing",
  "stage_whatsapp": "WhatsApp sent",
  "stage_critical": "Critical",
  "risk_unpaid": "Unpaid",
  "risk_prepaid": "Paid",
  "auto_cancel_reason": "Auto-cancelled — no action within {{window}} minutes.",
  "purchase_blocked": "Purchase not authorised — {{reason}}",
  "purchase_reason_unpaid": "the order is unpaid and no override is on file",
  "purchase_reason_credit": "the customer is over their credit limit",
  "purchase_reason_alert": "the order has not been accepted yet",
  "purchase_allowed_paid": "payment verified",
  "purchase_allowed_override": "admin override on file",
  "override_label": "Authorise purchase without payment",
  "override_hint": "Say why. This is logged against your name.",
  "override_saved": "Purchase authorised.",
  "override_missing_reason": "A reason is required.",
  "wa_escalation": "mediBO: order {{order_code}} from {{customer}} for {{amount}} is UNPAID and has been waiting {{age}}. Open the app to accept or reject.",
  "settings_title": "New-order alerts",
  "settings_subtitle": "What rings, when it escalates, and who may buy on credit.",
  "section_timings": "Escalation",
  "section_credit": "Credit policy",
  "section_open": "Awaiting action",
  "section_log": "Purchase decisions",
  "field_rering": "Re-ring after (seconds)",
  "field_wa": "WhatsApp the admin after (seconds)",
  "field_critical": "Mark critical after (seconds)",
  "field_autocancel": "Auto-cancel unactioned after (minutes)",
  "field_ring_seconds": "Keep ringing for (seconds)",
  "field_ring_delay": "Wait for payment before ringing (seconds)",
  "field_established_limit": "Credit limit for established customers",
  "field_min_paid": "Paid orders before a customer is established",
  "field_prepaid_new": "New customers are prepaid-only",
  "field_enforce": "Enforce the credit block",
  "field_gate": "Require payment or an override before buying",
  "field_enabled": "Alerts enabled",
  "saved": "Saved."
}$lbl$::jsonb,
       updated_at = now(),
       updated_by = 'change_306'
 where id = 'singleton';

-- The one delay the engine needs and the table did not have: how long to wait
-- for a gateway payment before deciding an order is genuinely unpaid.
alter table public.order_alert_config
  add column if not exists ring_delay_s integer not null default 90;
