-- CMD #466 — the five APPROVED medium/partner feature_gaps rows, closed.
--
--   147  notif_cost_dashboard answered a partner  -> fenced on role_for_medibo_only()
--   150  no partner statement DOCUMENT            -> partner_document + bill-render
--   151  no earnings surface for a partner        -> already live (partner.settlement)
--   153  no licence expiry / renewal reminder     -> expiry columns + daily sweep
--   154  no partner suspension / offboarding      -> partner_suspend / partner_resume
--
-- Everything here is idempotent: a resumed worker re-applies it as a no-op.

-- ─────────────────────────────────────────────────────────────────────────────
-- COPY. Every string a screen prints lives here, never in Dart.
-- ─────────────────────────────────────────────────────────────────────────────
insert into public.ui_copy(key, value) values
  ('partner_lifecycle.heading',        to_jsonb('Partner status'::text)),
  ('partner_lifecycle.active_label',   to_jsonb('Active'::text)),
  ('partner_lifecycle.suspended_label',to_jsonb('Suspended'::text)),
  ('partner_lifecycle.inactive_label', to_jsonb('Not active'::text)),
  ('partner_lifecycle.suspend_label',  to_jsonb('Suspend partner'::text)),
  ('partner_lifecycle.resume_label',   to_jsonb('Resume partner'::text)),
  ('partner_lifecycle.reason_hint',    to_jsonb('Why is this partner being suspended?'::text)),
  ('partner_lifecycle.err_no_reason',  to_jsonb('A suspension needs a reason.'::text)),
  ('partner_lifecycle.err_not_authorized', to_jsonb('Only mediBO staff can change a partner''s status.'::text)),
  ('partner_lifecycle.err_no_partner', to_jsonb('That partner no longer exists.'::text)),
  ('partner_lifecycle.suspended_since',to_jsonb('Suspended {at} by {by}'::text)),
  ('partner_lifecycle.inflight_head',  to_jsonb('Orders already with this partner'::text)),
  ('partner_lifecycle.inflight_text',  to_jsonb('{n} order(s) are still open. They stay with this partner and are worked to close as normal — suspension stops NEW orders being routed here, it does not cancel work in hand.'::text)),
  ('partner_lifecycle.inflight_none',  to_jsonb('No open orders. Nothing is left to finish.'::text)),
  ('partner_lifecycle.balance_head',   to_jsonb('Open settlement balance'::text)),
  ('partner_lifecycle.balance_text',   to_jsonb('{amt} across {n} unsettled period(s). Suspension does not freeze it — every period already earned is computed and paid on the normal cadence.'::text)),
  ('partner_lifecycle.balance_none',   to_jsonb('Nothing outstanding. Every period is settled.'::text)),
  ('partner_lifecycle.routing_head',   to_jsonb('New work'::text)),
  ('partner_lifecycle.routing_text',   to_jsonb('New orders in this zone are routed to the next active partner from the moment the suspension is saved.'::text)),
  ('partner_lifecycle.suspended_toast',to_jsonb('Partner suspended. New orders will not be routed here.'::text)),
  ('partner_lifecycle.resumed_toast',  to_jsonb('Partner resumed. New orders route here again.'::text)),

  ('partner_licence.heading',          to_jsonb('Licences and expiry'::text)),
  ('partner_licence.sub',              to_jsonb('A partner cannot trade on a lapsed licence. Set the expiry and mediBO reminds them before it runs out.'::text)),
  ('partner_licence.gstin_label',      to_jsonb('GSTIN'::text)),
  ('partner_licence.dl_20b_label',     to_jsonb('Drug Licence 20B'::text)),
  ('partner_licence.dl_21b_label',     to_jsonb('Drug Licence 21B'::text)),
  ('partner_licence.agreement_label',  to_jsonb('Signed agreement'::text)),
  ('partner_licence.no_expiry',        to_jsonb('No expiry recorded'::text)),
  ('partner_licence.no_number',        to_jsonb('Not captured'::text)),
  ('partner_licence.valid_label',      to_jsonb('Valid to {d}'::text)),
  ('partner_licence.due_label',        to_jsonb('Expires in {n} day(s) — {d}'::text)),
  ('partner_licence.expired_label',    to_jsonb('Expired on {d}'::text)),
  ('partner_licence.set_label',        to_jsonb('Set expiry'::text)),
  ('partner_licence.ok_all',           to_jsonb('All licences current'::text)),
  ('partner_licence.alert_due',        to_jsonb('{n} licence(s) expiring within {w} days'::text)),
  ('partner_licence.alert_expired',    to_jsonb('{n} licence(s) have expired'::text)),
  ('partner_licence.err_kind',         to_jsonb('That is not a licence mediBO tracks.'::text)),
  ('partner_licence.saved_toast',      to_jsonb('Expiry saved.'::text)),
  ('partner_licence.reminder_title',   to_jsonb('Licence renewal due'::text)),
  ('partner_licence.reminder_body',    to_jsonb('{label} for {partner} expires on {d}. Renew it and send mediBO the new copy.'::text)),

  ('partner_doc.title',                to_jsonb('Statement'::text)),
  ('partner_doc.button',               to_jsonb('Download statement'::text)),
  ('partner_doc.building_message',     to_jsonb('Building your statement…'::text)),
  ('partner_doc.ready_message',        to_jsonb('Statement ready.'::text)),
  ('partner_doc.err_unknown_kind',     to_jsonb('mediBO does not issue that document.'::text)),
  ('partner_doc.err_not_found',        to_jsonb('That statement is not available.'::text)),
  ('partner_doc.err_failed',           to_jsonb('The statement could not be built. Try again.'::text)),
  ('partner_doc.err_not_partner',      to_jsonb('Only a partner login can download a partner statement.'::text)),
  ('partner_doc.doc_title',            to_jsonb('Partner settlement statement — {period}'::text)),
  ('partner_doc.doc_subtitle',         to_jsonb('Generated {at} · mediBO'::text)),
  ('partner_doc.doc_brand',            to_jsonb('mediBO · Jai Mahakal Medical And Surgical'::text)),
  ('partner_doc.lbl_partner',          to_jsonb('Partner'::text)),
  ('partner_doc.lbl_gstin',            to_jsonb('Partner GSTIN'::text)),
  ('partner_doc.lbl_recipient',        to_jsonb('mediBO GSTIN'::text)),
  ('partner_doc.lbl_period',           to_jsonb('Period'::text)),
  ('partner_doc.lbl_statement_no',     to_jsonb('Statement no.'::text)),
  ('partner_doc.lbl_date',             to_jsonb('Issued'::text)),
  ('partner_doc.lbl_pos',              to_jsonb('Place of supply'::text)),
  ('partner_doc.lbl_sac',              to_jsonb('SAC'::text)),
  ('partner_doc.lbl_zone',             to_jsonb('Zone'::text)),
  ('partner_doc.no_gstin',             to_jsonb('Not registered'::text)),
  ('partner_doc.orders_heading',       to_jsonb('Orders fulfilled in this period'::text)),
  ('partner_doc.orders_empty',         to_jsonb('No orders were settled in this period.'::text)),
  ('partner_doc.col_date',             to_jsonb('Date'::text)),
  ('partner_doc.col_order',            to_jsonb('Order'::text)),
  ('partner_doc.col_revenue',          to_jsonb('Gross value'::text)),
  ('partner_doc.col_margin',           to_jsonb('Margin'::text)),
  ('partner_doc.col_share',            to_jsonb('Your share'::text)),
  ('partner_doc.costs_heading',        to_jsonb('Deductions'::text)),
  ('partner_doc.costs_empty',          to_jsonb('No deductions in this period.'::text)),
  ('partner_doc.col_cost_label',       to_jsonb('Deduction'::text)),
  ('partner_doc.col_cost_amount',      to_jsonb('Amount'::text)),
  ('partner_doc.lbl_orders',           to_jsonb('Orders fulfilled'::text)),
  ('partner_doc.lbl_gross',            to_jsonb('Gross order value'::text)),
  ('partner_doc.lbl_margin',           to_jsonb('Gross margin'::text)),
  ('partner_doc.lbl_costs',            to_jsonb('Less: costs'::text)),
  ('partner_doc.lbl_distributable',    to_jsonb('Distributable profit'::text)),
  ('partner_doc.lbl_split',            to_jsonb('Your split'::text)),
  ('partner_doc.lbl_commission',       to_jsonb('Commission earned (taxable value)'::text)),
  ('partner_doc.lbl_brought_forward',  to_jsonb('Brought forward'::text)),
  ('partner_doc.lbl_net',              to_jsonb('Net payable'::text)),
  ('partner_doc.gst_note_registered',  to_jsonb('GST: the commission above is the TAXABLE VALUE of a service you supply to mediBO. You are registered ({gstin}), so raise a tax invoice on mediBO for this amount plus GST at {rate}% (SAC {sac}); mediBO pays the commission and the tax against that invoice. This statement is not a tax invoice.'::text)),
  ('partner_doc.gst_note_unregistered',to_jsonb('GST: the commission above is the TAXABLE VALUE of a service you supply to mediBO. No GSTIN is recorded for you, so no tax is added and no tax invoice is expected. Give mediBO your GSTIN if you are registered. This statement is not a tax invoice.'::text)),
  ('partner_doc.gst_head',             to_jsonb('GST on the commission'::text)),
  ('partner_doc.gst_taxable',          to_jsonb('Taxable value'::text)),
  ('partner_doc.gst_cgst',             to_jsonb('CGST'::text)),
  ('partner_doc.gst_sgst',             to_jsonb('SGST'::text)),
  ('partner_doc.gst_igst',             to_jsonb('IGST'::text)),
  ('partner_doc.gst_invoice_total',    to_jsonb('Invoice this on mediBO'::text)),
  ('partner_doc.footer',               to_jsonb('Computed from the settlement ledger. Every figure is the one snapshotted on the order at bill time — a later change to the deal never rewrites a past statement.'::text))
on conflict (key) do nothing;
