-- CHANGE #402 — the copy: English for every new key, Hindi for the
-- supplier-facing surfaces. Generated seed; re-running it is a no-op.
--
-- English lives in ui_copy and is the guaranteed fallback. Hindi lives in
-- ui_copy_i18n. A key with no Hindi row is not a bug — it is a row in
-- ui_language_report(), which is exactly how the gap stays visible.

with seed(k, en, hi) as (values
  ('supplier_lang.title', 'Language', 'भाषा'),
  ('supplier_lang.subtitle', 'Choose the language for your screens. The messages we send you follow the same choice.', 'अपनी स्क्रीन की भाषा चुनें। हम जो संदेश भेजते हैं वे भी इसी भाषा में आएंगे।'),
  ('supplier_lang.open_label', 'Language', 'भाषा'),
  ('supplier_lang.saved', 'Language changed', 'भाषा बदल दी गई'),
  ('supplier_lang.err_not_signed_in', 'Sign in to change the language.', 'भाषा बदलने के लिए साइन इन करें।'),
  ('supplier_lang.err_unknown', 'That language is not available.', 'यह भाषा उपलब्ध नहीं है।'),
  ('supplier_lang.err_failed', 'Could not save: {detail}', 'सहेजा नहीं जा सका: {detail}'),
  ('supplier_staff.feature_label', 'Staff', 'स्टाफ'),
  ('supplier_staff.title', 'My staff', 'मेरा स्टाफ'),
  ('supplier_staff.subtitle', 'Extra logins for your shop. Each one sees only what you allow.', 'आपकी दुकान के लिए अतिरिक्त लॉगिन। हर व्यक्ति को केवल वही दिखेगा जिसकी आप अनुमति देंगे।'),
  ('supplier_staff.add_label', 'Add staff login', 'स्टाफ लॉगिन जोड़ें'),
  ('supplier_staff.add_hint', 'Email or 10-digit mobile', 'ईमेल या 10 अंकों का मोबाइल नंबर'),
  ('supplier_staff.name_hint', 'Name (optional)', 'नाम (वैकल्पिक)'),
  ('supplier_staff.save_label', 'Add', 'जोड़ें'),
  ('supplier_staff.remove_label', 'Remove', 'हटाएं'),
  ('supplier_staff.role_label', 'Access', 'अनुमति'),
  ('supplier_staff.owner_label', 'Owner', 'मालिक'),
  ('supplier_staff.role_owner', 'Owner — full access', 'मालिक — पूरी अनुमति'),
  ('supplier_staff.role_inquiry_only', 'Inquiry only', 'केवल पूछताछ'),
  ('supplier_staff.role_inquiry_only_desc', 'Answer inquiries. Can see orders, cannot change them.', 'पूछताछ का जवाब दें। ऑर्डर देख सकते हैं, बदल नहीं सकते।'),
  ('supplier_staff.role_billing_only', 'Billing only', 'केवल बिलिंग'),
  ('supplier_staff.role_billing_only_desc', 'Orders, bills and disputes. Can see payout details, cannot change them.', 'ऑर्डर, बिल और शिकायतें। भुगतान विवरण देख सकते हैं, बदल नहीं सकते।'),
  ('supplier_staff.role_full', 'Full access', 'पूरी अनुमति'),
  ('supplier_staff.role_full_desc', 'Everything except staff and payout changes, which stay with you.', 'स्टाफ और भुगतान विवरण को छोड़कर सब कुछ — वे केवल आपके पास रहते हैं।'),
  ('supplier_staff.empty', 'No staff logins yet. Add one and they sign in with the same OTP or Google login you use.', 'अभी कोई स्टाफ लॉगिन नहीं है। एक जोड़ें — वे उसी OTP या Google लॉगिन से साइन इन करेंगे जिससे आप करते हैं।'),
  ('supplier_staff.added', 'Staff login added', 'स्टाफ लॉगिन जोड़ा गया'),
  ('supplier_staff.removed', 'Staff login removed', 'स्टाफ लॉगिन हटाया गया'),
  ('supplier_staff.role_saved', 'Access updated', 'अनुमति बदल दी गई'),
  ('supplier_staff.added_on', 'Added {date}', '{date} को जोड़ा गया'),
  ('supplier_staff.audit_heading', 'Recent activity', 'हाल की गतिविधि'),
  ('supplier_staff.audit_empty', 'Nothing yet.', 'अभी कुछ नहीं।'),
  ('supplier_staff.audit_added', '{who} added as {role}', '{who} को {role} के रूप में जोड़ा गया'),
  ('supplier_staff.audit_role', '{who} changed to {role}', '{who} की अनुमति {role} कर दी गई'),
  ('supplier_staff.audit_removed', '{who} removed', '{who} को हटाया गया'),
  ('supplier_staff.err_not_authorized', 'You do not have access to staff logins.', 'आपको स्टाफ लॉगिन की अनुमति नहीं है।'),
  ('supplier_staff.err_not_supplier', 'No supplier account found for this login.', 'इस लॉगिन के लिए कोई सप्लायर खाता नहीं मिला।'),
  ('supplier_staff.err_bad_identity', 'Enter a valid email or 10-digit mobile number.', 'सही ईमेल या 10 अंकों का मोबाइल नंबर डालें।'),
  ('supplier_staff.err_bad_role', 'Pick an access level.', 'अनुमति का स्तर चुनें।'),
  ('supplier_staff.err_identity_taken', 'That login already belongs to someone else.', 'यह लॉगिन पहले से किसी और का है।'),
  ('supplier_staff.err_already_owner', 'That is your own login.', 'यह आपका अपना लॉगिन है।'),
  ('supplier_staff.err_not_your_staff', 'That staff login is not yours.', 'यह स्टाफ लॉगिन आपका नहीं है।'),
  ('supplier_staff.err_cannot_remove_self', 'You cannot remove your own login.', 'आप अपना ही लॉगिन नहीं हटा सकते।'),
  ('supplier_staff.err_cannot_edit_self', 'You cannot change your own access.', 'आप अपनी ही अनुमति नहीं बदल सकते।'),
  ('supplier_staff.err_failed', 'Could not save: {detail}', 'सहेजा नहीं जा सका: {detail}'),
  ('supplier_shell.staff_badge', '{name} · staff', '{name} · स्टाफ'),
  ('supplier_payout.feature_label', 'Bank / UPI', 'बैंक / UPI'),
  ('supplier_payout.title', 'Payout details', 'भुगतान विवरण'),
  ('supplier_payout.subtitle', 'Where mediBO pays you. A change is checked by our team before it takes effect.', 'mediBO आपको यहां भुगतान करता है। बदलाव लागू होने से पहले हमारी टीम उसे जांचती है।'),
  ('supplier_payout.form_heading', 'New payout details', 'नए भुगतान विवरण'),
  ('supplier_payout.active_heading', 'In use now', 'अभी उपयोग में'),
  ('supplier_payout.pending_heading', 'Waiting for approval', 'मंजूरी का इंतजार'),
  ('supplier_payout.history_heading', 'Earlier details', 'पुराने विवरण'),
  ('supplier_payout.history_empty', 'No earlier details.', 'कोई पुराना विवरण नहीं।'),
  ('supplier_payout.empty', 'No payout details on file yet. Add them so payments reach you without asking.', 'अभी कोई भुगतान विवरण दर्ज नहीं है। जोड़ें ताकि भुगतान बिना पूछे आप तक पहुंचे।'),
  ('supplier_payout.pending_note', 'We are checking this. Your current details keep being used until it is approved.', 'हम इसे जांच रहे हैं। मंजूरी मिलने तक आपके मौजूदा विवरण ही उपयोग होते रहेंगे।'),
  ('supplier_payout.readonly_note', 'You can see these details but not change them.', 'आप ये विवरण देख सकते हैं, बदल नहीं सकते।'),
  ('supplier_payout.submit_label', 'Submit for approval', 'मंजूरी के लिए भेजें'),
  ('supplier_payout.f_account_name', 'Account holder name', 'खाताधारक का नाम'),
  ('supplier_payout.h_account_name', 'Exactly as printed in the bank passbook', 'बैंक पासबुक में छपे नाम के अनुसार'),
  ('supplier_payout.f_account_number', 'Account number', 'खाता संख्या'),
  ('supplier_payout.h_account_number', '9 to 18 digits', '9 से 18 अंक'),
  ('supplier_payout.f_ifsc', 'IFSC', 'IFSC कोड'),
  ('supplier_payout.h_ifsc', 'e.g. HDFC0001234', 'जैसे HDFC0001234'),
  ('supplier_payout.f_bank_name', 'Bank name', 'बैंक का नाम'),
  ('supplier_payout.h_bank_name', 'Optional', 'वैकल्पिक'),
  ('supplier_payout.f_upi_vpa', 'UPI ID', 'UPI आईडी'),
  ('supplier_payout.h_upi_vpa', 'e.g. shopname@okhdfcbank', 'जैसे shopname@okhdfcbank'),
  ('supplier_payout.status_pending', 'Waiting for approval', 'मंजूरी का इंतजार'),
  ('supplier_payout.status_active', 'In use', 'उपयोग में'),
  ('supplier_payout.status_rejected', 'Not approved', 'मंजूर नहीं'),
  ('supplier_payout.status_superseded', 'Replaced', 'बदल दिया गया'),
  ('supplier_payout.match_exact', 'Name matches {name}', 'नाम {name} से मेल खाता है'),
  ('supplier_payout.match_close', 'Name is close to {name} — our team will confirm', 'नाम {name} से लगभग मिलता है — हमारी टीम पुष्टि करेगी'),
  ('supplier_payout.match_differs', 'Name does not match {name} — our team will confirm', 'नाम {name} से मेल नहीं खाता — हमारी टीम पुष्टि करेगी'),
  ('supplier_payout.match_unknown', 'Name could not be checked', 'नाम की जांच नहीं हो सकी'),
  ('supplier_payout.submitted_on', 'Sent {date} by {who}', '{who} द्वारा {date} को भेजा गया'),
  ('supplier_payout.reviewed_on', 'Reviewed {date} by {who}', '{who} द्वारा {date} को जांचा गया'),
  ('supplier_payout.submitted', 'Sent for approval', 'मंजूरी के लिए भेज दिया गया'),
  ('supplier_payout.audit_submitted', '{who} submitted new payout details', '{who} ने नए भुगतान विवरण भेजे'),
  ('supplier_payout.audit_approve', '{who} approved the payout details', '{who} ने भुगतान विवरण मंजूर किए'),
  ('supplier_payout.audit_reject', '{who} rejected the payout details', '{who} ने भुगतान विवरण अस्वीकार किए'),
  ('supplier_payout.notify_title', 'Supplier payout details changed', null),
  ('supplier_payout.notify_body', '{supplier} — {who} submitted new bank/UPI details for approval.', null),
  ('supplier_payout.err_not_authorized', 'You do not have access to payout details.', 'आपको भुगतान विवरण की अनुमति नहीं है।'),
  ('supplier_payout.err_name_required', 'Enter the account holder name.', 'खाताधारक का नाम डालें।'),
  ('supplier_payout.err_need_one', 'Enter a bank account or a UPI ID.', 'बैंक खाता या UPI आईडी डालें।'),
  ('supplier_payout.err_bad_account', 'Account number must be 9 to 18 digits.', 'खाता संख्या 9 से 18 अंकों की होनी चाहिए।'),
  ('supplier_payout.err_bad_ifsc', 'Enter a valid IFSC, e.g. HDFC0001234.', 'सही IFSC कोड डालें, जैसे HDFC0001234।'),
  ('supplier_payout.err_bad_vpa', 'Enter a valid UPI ID, e.g. shopname@okhdfcbank.', 'सही UPI आईडी डालें, जैसे shopname@okhdfcbank।'),
  ('supplier_payout.err_failed', 'Could not save: {detail}', 'सहेजा नहीं जा सका: {detail}'),
  ('admin_payout.title', 'Supplier payout approvals', null),
  ('admin_payout.subtitle', 'New bank / UPI details waiting for a decision. Nothing is paid to them until approved.', null),
  ('admin_payout.empty', 'Nothing waiting.', null),
  ('admin_payout.approve', 'Approve', null),
  ('admin_payout.reject', 'Reject', null),
  ('admin_payout.note_hint', 'Note (optional)', null),
  ('admin_payout.current_heading', 'In use now', null),
  ('admin_payout.approved', 'Approved — this is now the account we pay', null),
  ('admin_payout.rejected', 'Rejected — the current details stay in use', null),
  ('admin_payout.err_not_pending', 'That request is no longer waiting.', null),
  ('admin_payout.err_bad_decision', 'Pick approve or reject.', null),
  ('admin_payout.on_file', 'Approved payout details on file', null),
  ('admin_payout.none_on_file', 'No approved payout details — ask the supplier to add them', null),
  ('admin_i18n.title', 'Hindi coverage', null),
  ('admin_i18n.subtitle', 'Supplier-facing keys and whether they carry a Hindi value. A missing key renders in English.', null),
  ('admin_i18n.headline', '{done} of {total} translated ({pct}%)', null),
  ('admin_i18n.missing_heading', 'Missing Hindi', null),
  ('admin_i18n.empty', 'Nothing missing — every supplier key has Hindi.', null),
  ('admin_i18n.save', 'Save', null),
  ('admin_i18n.hint', 'Type the Hindi and save. It is live on the next boot — no deploy.', null),
  ('admin_i18n.saved', 'Saved', null),
  ('admin_i18n.err_not_authorized', 'Admins only.', null),
  ('admin_i18n.err_unknown_key', 'That key does not exist.', null),
  ('admin_supplier_account.title', 'Supplier accounts', null),
  ('admin_supplier_account.tab_payouts', 'Payout approvals', null),
  ('admin_supplier_account.tab_language', 'Hindi coverage', null),
  ('supplier_shell.brand', null, 'mediBO'),
  ('supplier_shell.greeting', null, 'नमस्ते, {name}'),
  ('supplier_shell.role_badge', null, 'सप्लायर'),
  ('supplier_shell.supplier_fallback_name', null, 'सप्लायर'),
  ('supplier_shell.tab_add_medicine', null, 'दवा जोड़ें'),
  ('supplier_shell.tab_disputes', null, 'शिकायतें'),
  ('supplier_shell.tab_home', null, 'होम'),
  ('supplier_shell.tab_inquiry', null, 'पूछताछ'),
  ('supplier_shell.tab_orders', null, 'ऑर्डर'),
  ('supplier_shell.viewas_readonly', null, 'दवा जोड़ें (प्रीव्यू में केवल देखने के लिए)'),
  ('supplier_home.empty_no_companies', null, 'आपकी रखी हुई कंपनियों की कोई दवा अभी नहीं है।'),
  ('supplier_home.empty_no_companies_hint', null, 'अपने एडमिन से कहें कि आपकी प्रोफ़ाइल से कंपनियां जोड़ दें।'),
  ('supplier_home.empty_search', null, '"{query}" से कोई दवा नहीं मिली'),
  ('supplier_home.mrp', null, 'MRP ₹{mrp}'),
  ('supplier_home.search_hint', null, 'अपनी कंपनियों की दवाएं खोजें…'),
  ('supplier_disputes.cancel', null, 'रद्द करें'),
  ('supplier_disputes.confirm', null, 'पक्का करें'),
  ('supplier_disputes.confirm_body', null, '{product}
पक्का करें: {action}?'),
  ('supplier_disputes.empty', null, 'इस सप्लायर की कोई शिकायत नहीं।'),
  ('supplier_disputes.load_failed', null, 'शिकायतें लोड नहीं हो सकीं।'),
  ('supplier_disputes.no_active', null, 'कोई चालू शिकायत नहीं।'),
  ('supplier_disputes.no_supplier', null, 'कोई सप्लायर खाता नहीं मिला।'),
  ('supplier_disputes.proof_photo', null, 'सबूत की फोटो:'),
  ('supplier_disputes.qty_missing', null, 'कम मिला'),
  ('supplier_disputes.qty_ordered', null, 'ऑर्डर किया'),
  ('supplier_disputes.qty_received', null, 'मिला'),
  ('supplier_disputes.refresh', null, 'फिर से लोड करें'),
  ('supplier_disputes.retry', null, 'दोबारा कोशिश करें'),
  ('supplier_disputes.section_active', null, 'चालू'),
  ('supplier_disputes.section_count', null, '({count})'),
  ('supplier_disputes.snack_recorded', null, 'दर्ज हुआ: {result}'),
  ('supplier_disputes.viewing_as', null, '{name} के रूप में देख रहे हैं (एडमिन)'),
  ('supplier_disputes.wrong_product', null, 'उनका कहना है कि हमने भेजा: {name}'),
  ('supplier_disputes_page.empty', null, 'कोई शिकायत नहीं 🎉'),
  ('supplier_disputes_page.load_failed', null, 'शिकायतें लोड नहीं हो सकीं।'),
  ('supplier_disputes_page.no_supplier', null, 'कोई सप्लायर खाता नहीं मिला।'),
  ('supplier_disputes_page.recorded', null, 'दर्ज हुआ'),
  ('supplier_disputes_page.refresh', null, 'फिर से लोड करें'),
  ('supplier_disputes_page.retry', null, 'दोबारा कोशिश करें'),
  ('supplier_disputes_page.viewing_as_admin', null, '{a} के रूप में देख रहे हैं (एडमिन)'),
  ('supplier_orders.bill_default_name', null, 'बिल'),
  ('supplier_orders.bill_unavailable', null, 'बिल उपलब्ध नहीं है।'),
  ('supplier_orders.cancel', null, 'रद्द करें'),
  ('supplier_orders.delete', null, 'हटाएं'),
  ('supplier_orders.delete_bill', null, 'बिल हटाएं'),
  ('supplier_orders.delete_bill_body', null, 'इससे अपलोड किया गया बिल हट जाएगा। यह वापस नहीं आएगा।'),
  ('supplier_orders.delete_bill_title', null, 'बिल हटाएं?'),
  ('supplier_orders.deleting', null, 'हटाया जा रहा है…'),
  ('supplier_orders.download', null, 'डाउनलोड'),
  ('supplier_orders.downloading', null, 'डाउनलोड हो रहा है…'),
  ('supplier_orders.empty', null, 'अभी कोई ऑर्डर नहीं।'),
  ('supplier_orders.imported', null, 'आयात हो चुका'),
  ('supplier_orders.no_items', null, 'कोई आइटम नहीं।'),
  ('supplier_orders.order', null, 'ऑर्डर'),
  ('supplier_orders.order_no', null, 'ऑर्डर {no}'),
  ('supplier_orders.panel_failed', null, 'लोड नहीं हो सका।'),
  ('supplier_orders.payment_summary', null, 'भुगतान का ब्यौरा'),
  ('supplier_orders.payment_unavailable', null, 'भुगतान का ब्यौरा उपलब्ध नहीं है।'),
  ('supplier_orders.retry', null, 'दोबारा कोशिश करें'),
  ('supplier_orders.share', null, 'भेजें'),
  ('supplier_orders.sharing', null, 'भेजा जा रहा है…'),
  ('supplier_orders.toast_bill_already_imported', null, 'यह बिल आयात हो चुका है, अब हटाया नहीं जा सकता।'),
  ('supplier_orders.toast_bill_deleted', null, 'बिल हटा दिया गया'),
  ('supplier_orders.toast_bill_load_failed', null, 'बिल लोड नहीं हो सका।'),
  ('supplier_orders.toast_bill_not_registered', null, 'बिल सहेजा गया पर दर्ज नहीं हुआ — mediBO से संपर्क करें'),
  ('supplier_orders.toast_bill_uploaded', null, 'बिल अपलोड हो गया ✓'),
  ('supplier_orders.toast_delete_failed', null, 'बिल हटाया नहीं जा सका'),
  ('supplier_orders.toast_file_too_large', null, 'फाइल बहुत बड़ी है (अधिकतम 15 MB)'),
  ('supplier_orders.toast_pack_failed', null, 'पैक की स्थिति बदली नहीं जा सकी'),
  ('supplier_orders.toast_upload_failed', null, 'अपलोड नहीं हुआ — दोबारा कोशिश करें'),
  ('supplier_orders.upload_bill', null, 'बिल अपलोड करें'),
  ('supplier_orders.uploading', null, 'अपलोड हो रहा है…'),
  ('supplier_orders.view_bill', null, 'बिल देखें'),
  ('supplier_orders.view_payment', null, 'भुगतान देखें'),
  ('supplier.avail_close_btn', null, 'दुकान बंद दर्ज करें'),
  ('supplier.avail_history_title', null, 'पिछले 90 दिनों में आपकी बंदी'),
  ('supplier.avail_intro', null, 'अपनी दुकान बंद दर्ज करें और जब तक आप दोबारा नहीं खोलते, हम आपको पूछताछ नहीं भेजेंगे। बंद रहने पर कोई नुकसान नहीं — न जवाब छूटने का निशान, न रैंकिंग में गिरावट।'),
  ('supplier.avail_reason_hint', null, 'कारण (वैकल्पिक) — जैसे छुट्टी, स्टॉक गिनती'),
  ('supplier.avail_reopen_btn', null, 'दुकान दोबारा खोलें'),
  ('supplier.avail_title', null, 'दुकान की उपलब्धता'),
  ('supplier.avail_until_hint', null, 'कब तक बंद (अभी पता न हो तो खाली छोड़ दें)'),
  ('supplier.closed_bad_range', null, 'यह दोबारा खोलने का समय बीत चुका है। आगे का समय चुनें, या खाली छोड़ दें।'),
  ('supplier.closed_history', null, 'पिछले 90 दिनों में {n} बार बंद, कुल {days} दिन'),
  ('supplier.closed_history_none', null, 'पिछले 90 दिनों में कोई बंदी नहीं'),
  ('supplier.closed_label', null, '{until} तक बंद'),
  ('supplier.closed_open_label', null, 'खुली — पूछताछ आ रही है'),
  ('supplier.closed_reason', null, 'कारण: {reason}'),
  ('supplier.closed_toast', null, 'दुकान बंद दर्ज हो गई। दोबारा खोलने तक कोई पूछताछ नहीं आएगी।'),
  ('supplier.closed_until_reopen', null, 'आप दोबारा खोलें'),
  ('supplier.cov_add', null, 'जोड़ें'),
  ('supplier.cov_added', null, '{company} जोड़ी गई। इसके लिए आपसे पहले पूछा जाएगा।'),
  ('supplier.cov_any_company', null, 'कोई भी कंपनी'),
  ('supplier.cov_declared_empty', null, 'अभी कुछ दर्ज नहीं है। नीचे एक कंपनी जोड़ें, फिर उसके लिए आपसे पहले पूछा जाएगा।'),
  ('supplier.cov_declared_title', null, 'आप ये रखते हैं'),
  ('supplier.cov_excluded_note', null, 'ये बंद ही रहेंगी। ऊपर कंपनी जोड़ने से ये वापस नहीं आतीं।'),
  ('supplier.cov_excluded_title', null, 'आपने बताया कि ये आप नहीं रखते'),
  ('supplier.cov_intro', null, 'हमें बताएं आप कौन सी कंपनियां रखते हैं, तो उन दवाओं के लिए हम आपसे पहले पूछेंगे। खाली छोड़ने पर कोई नुकसान नहीं — पूछा फिर भी जाएगा, बस उन दुकानों के बाद जिन्होंने कंपनी दर्ज की है।'),
  ('supplier.cov_remove', null, 'हटाएं'),
  ('supplier.cov_removed', null, '{company} हटा दी गई।'),
  ('supplier.cov_suggest_empty', null, 'अभी कोई सुझाव नहीं — कुछ पूछताछ के जवाब देने पर दिखेंगे।'),
  ('supplier.cov_suggest_sub', null, 'आपने {n} बार उपलब्ध बताया'),
  ('supplier.cov_suggest_title', null, 'आपके पिछले जवाबों से सुझाव'),
  ('supplier.cov_tile_n', null, '{n} दर्ज'),
  ('supplier.cov_tile_none', null, 'अभी कुछ दर्ज नहीं'),
  ('supplier.cov_title', null, 'आप जो कंपनियां रखते हैं'),
  ('supplier.cov_too_broad', null, 'कोई कंपनी या श्रेणी चुनें — "सब कुछ" पर रैंकिंग नहीं बन सकती।'),
  ('supplier.packed_toast', null, 'पैक दर्ज हो गया। धन्यवाद।'),
  ('supplier.parcels_bad', null, 'पार्सल की संख्या ऋणात्मक नहीं हो सकती।'),
  ('supplier.parcels_hint', null, 'कितने पार्सल? (वैकल्पिक)'),
  ('supplier.parcels_n', null, '{n} पार्सल'),
  ('supplier.ready_at', null, '{time} से तैयार'),
  ('supplier.ready_hint', null, 'उठाने के लिए कब से तैयार (वैकल्पिक)'),
  ('supplier.ready_now', null, 'अभी तैयार'),
  ('supplier.ready_unknown', null, 'तैयार होने का समय नहीं बताया'),
  ('supplier.reopen_toast', null, 'दुकान दोबारा खुल गई। आप पूछताछ सूची में वहीं हैं जहां थे।'),
  ('supplier.run_empty', null, 'आज कोई कलेक्शन बाकी नहीं।'),
  ('supplier.run_intro', null, 'उठाने के क्रम में स्टॉप — जिन दुकानों ने तैयार समय बताया है वे पहले, फिर रोज़ का रास्ता।'),
  ('supplier.run_parcels_total', null, 'आज {n} पार्सल उठाने हैं'),
  ('supplier.run_title', null, 'कलेक्ट रन'),
  ('supplier.unpacked_toast', null, 'पैक का निशान हटा दिया गया।'),
  ('supplier_po.basis_empty', null, 'इस ऑर्डर में अभी कोई लाइन नहीं'),
  ('supplier_po.basis_line_catalog', null, 'कैटलॉग ट्रेड रेट'),
  ('supplier_po.basis_line_pending', null, 'रेट बाकी — MRP पर दिखाया गया'),
  ('supplier_po.basis_line_quote', null, 'सप्लायर रेट'),
  ('supplier_po.basis_mixed', null, 'कुछ लाइनों का सप्लायर रेट अभी बाकी है'),
  ('supplier_po.basis_mrp', null, 'रेट बाकी — कुल राशि MRP पर अस्थायी है'),
  ('supplier_po.basis_quote', null, 'सप्लायर के बताए रेट पर'),
  ('supplier_po.mrp_column', null, 'MRP'),
  ('supplier_po.mrp_note', null, 'MRP छपी हुई अधिकतम सीमा है — केवल संदर्भ के लिए, कभी ट्रेड रेट नहीं'),
  ('supplier_po.payable_label', null, 'देय'),
  ('supplier_po.rate_column', null, 'रेट'),
  ('supplier_po.rate_pending_dash', null, '—'),
  ('supplier_map_groups.toast_open_route_tab_first', null, 'पहले एक बार Customer → Route टैब खोलें, फिर दोबारा कोशिश करें।'),
  ('supplier_map_groups.toast_optimizing', null, 'रास्ते बनाए जा रहे हैं — प्रगति के लिए Customer → Route टैब देखें।')
)
, up_en as (
  insert into public.ui_copy(key, value, updated_at)
  select k, to_jsonb(en), now() from seed where en is not null
  on conflict (key) do update set value = excluded.value, updated_at = now()
  returning 1)
insert into public.ui_copy_i18n(key, lang, value, source, updated_by, updated_at)
select k, 'hi', to_jsonb(hi), 'seed', 'c402', now() from seed where hi is not null
on conflict (key, lang) do update
  set value = excluded.value, source = 'seed', updated_at = now();

-- The scopes the report measures: the REAL supplier key prefixes, which are
-- what the screens actually use (an invented prefix measures nothing).
delete from public.ui_i18n_scope where prefix not in (
  'supplier.','supplier_shell.','supplier_home.','supplier_orders.',
  'supplier_disputes.','supplier_disputes_page.','supplier_add_medicine.',
  'supplier_po.','supplier_map_groups.','supplier_staff.','supplier_payout.',
  'supplier_lang.');
insert into public.ui_i18n_scope(prefix, label, sort_order, is_active) values
  ('supplier_shell.','Supplier shell',10,true),
  ('supplier_home.','Supplier home',20,true),
  ('supplier.','Supplier availability & coverage',30,true),
  ('supplier_orders.','Supplier orders',40,true),
  ('supplier_po.','Supplier purchase order',45,true),
  ('supplier_disputes.','Supplier disputes',50,true),
  ('supplier_disputes_page.','Supplier disputes (portal)',55,true),
  ('supplier_add_medicine.','Supplier add medicine',60,true),
  ('supplier_map_groups.','Supplier map groups',65,true),
  ('supplier_staff.','Supplier staff',70,true),
  ('supplier_payout.','Supplier payout',80,true),
  ('supplier_lang.','Language switch',90,true)
on conflict (prefix) do update
  set label = excluded.label, sort_order = excluded.sort_order, is_active = true;
