-- CHANGE #713 (3/8) — every word the two screens print.
--
-- There is not one display string in the Dart. "mediBO" is here because the
-- decision "the customer sees one counterparty" is a business decision, and a
-- rename is an UPDATE rather than a deploy.

insert into public.ui_copy (key, value) values
  ('thread.title',            '"Messages"'::jsonb),
  ('thread.order_label',      '"Order {code}"'::jsonb),
  ('thread.brand',            '"mediBO"'::jsonb),
  ('thread.you',              '"You"'::jsonb),
  ('thread.brand_note',       '"You are talking to the mediBO team for this order."'::jsonb),
  ('thread.actor_admin',      '"mediBO office"'::jsonb),
  ('thread.actor_partner',    '"mediBO partner"'::jsonb),
  ('thread.actor_customer',   '"Customer"'::jsonb),
  ('thread.actor_system',     '"mediBO"'::jsonb),
  ('thread.via_whatsapp',     '"via WhatsApp"'::jsonb),
  ('thread.read',             '"Read"'::jsonb),
  ('thread.unread',           '"Not read yet"'::jsonb),
  ('thread.attach_open',      '"Open"'::jsonb),
  ('thread.compose_hint',     '"Write a message"'::jsonb),
  ('thread.send_cta',         '"Send"'::jsonb),
  ('thread.attach_cta',       '"Attach a photo"'::jsonb),
  ('thread.sent_toast',       '"Sent"'::jsonb),
  ('thread.empty_title',      '"No messages yet"'::jsonb),
  ('thread.empty_note',       '"Ask us anything about this order — we reply here."'::jsonb),
  ('thread.status_open',      '"Waiting on us"'::jsonb),
  ('thread.status_answered',  '"Answered"'::jsonb),
  ('thread.status_closed',    '"Closed"'::jsonb),
  ('thread.owner_none',       '"Unassigned"'::jsonb),
  ('thread.owner_admin',      '"mediBO office"'::jsonb),
  ('thread.sla_clear',        '"Nothing waiting"'::jsonb),
  ('thread.sla_due',          '"Reply due by {at}"'::jsonb),
  ('thread.sla_breached',     '"Overdue by {age}"'::jsonb),
  ('thread.sla_escalated',    '"Escalated to the office · waiting {age}"'::jsonb),
  ('thread.err_not_yours',    '"This conversation is not yours to open."'::jsonb),
  ('thread.err_no_thread',    '"There is no conversation for this order yet."'::jsonb),
  ('thread.err_empty',        '"Write something first."'::jsonb),
  -- the inbox
  ('thread.inbox_title',      '"Customer messages"'::jsonb),
  ('thread.inbox_empty_title','"Nothing waiting"'::jsonb),
  ('thread.inbox_empty_note', '"Every customer message in your zone has been answered."'::jsonb),
  ('thread.inbox_all',        '"All"'::jsonb),
  ('thread.inbox_waiting',    '"Waiting"'::jsonb),
  ('thread.inbox_breached',   '"Overdue"'::jsonb),
  ('thread.inbox_answered',   '"Answered"'::jsonb),
  ('thread.inbox_zone_all',   '"All zones"'::jsonb),
  ('thread.nav_badge_label',  '"{n} waiting"'::jsonb),
  ('thread.last_by_customer', '"Customer"'::jsonb),
  ('thread.last_by_us',       '"Us"'::jsonb),
  -- call tasks
  ('thread.tasks_title',      '"Calls to make"'::jsonb),
  ('thread.tasks_empty_title','"No calls to make"'::jsonb),
  ('thread.tasks_empty_note', '"A critical message nobody has read, or a missed call, appears here."'::jsonb),
  ('thread.task_unread_critical', '"{what} not read — call the customer"'::jsonb),
  ('thread.task_missed_callback', '"Missed call from the customer — call back"'::jsonb),
  ('thread.task_due',         '"Due by {at}"'::jsonb),
  ('thread.task_overdue',     '"Overdue by {age}"'::jsonb),
  ('thread.task_log_cta',     '"Log the outcome"'::jsonb),
  ('thread.task_logged_toast','"Outcome saved"'::jsonb),
  ('thread.task_note_hint',   '"Anything worth writing down"'::jsonb),
  ('thread.task_gone',        '"That call task is already closed."'::jsonb),
  ('thread.critical_payment_due',  '"The payment reminder"'::jsonb),
  ('thread.critical_delivery_otp', '"The delivery OTP"'::jsonb),
  ('thread.critical_sourcing_done','"The sourcing update"'::jsonb),
  ('thread.critical_return_decision','"The return decision"'::jsonb),
  -- escalation + WhatsApp nudge
  ('thread.escalated_system_line', '"No reply within {mins} minutes — escalated to the mediBO office."'::jsonb),
  ('thread.customer_action_label', '"Messages"'::jsonb)
on conflict (key) do update set value = excluded.value, updated_at = now();
